version: "3"

services:
  mongo:
    container_name: mongo_planets_db
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    command: mongod --quiet --logpath /dev/null
  service:
    container_name: planet_api
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
